title: Afonso Rodrigues blog's
email: afonsoaugustoventura@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Este blog se destina para conter anotações e atalhos de script e dicas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Afonsoavr
github_username:  afonsoaugusto

# Build settings
markdown: kramdown
permalink:   /:categories/:title/
theme: minima
#remote_theme: afonsoaugusto/plainwhite-jekyll
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-seo-tag

minima:
  name: Afonso Rodrigues
  date_format: "%b %-d, %Y"

  social_links:
    twitter: Afonsoavr
    github:  afonsoaugusto
    linkedIn: in/afonsoavr # format: locale/username
    instagram: afonsoavr
    stackoverflow: afonsoavr
    telegram: afonsoavr
  
comments:
   provider: disqus    
disqus:
  shortname: afonsoaugusto-github-io
