title: Afonso Rodrigues blog's
email: afonsoaugustoventura@gmail.com
description: >-
  Anotações, Scripts e Dicas de DevOps, SRE, Kubernetes e AWS
baseurl: "" # subcaminho, se necessário (ex: /blog)
url: "https://afonsorodrigues.com" # URL principal do site

lang: "pt-BR"
encoding: "utf-8"

twitter_username: Afonsoavr
github_username: afonsoaugusto

# SEO
seo:
  type: "Person"
  name: "Afonso Rodrigues"
  description: "Anotações, Scripts e Dicas de DevOps e SRE"
  url: "https://afonsorodrigues.com"
  twitter: "@Afonsoavr"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
remote_theme: jekyll/minima@latest

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-remote-include
  - jekyll-include-cache
  - jekyll-paginate-v2
  - kramdown
  - rouge

highlighter: rouge

kramdown:
  input: GFM

minima:
  name: Afonso Rodrigues
  social_links:
    twitter: Afonsoavr
    github: afonsoaugusto
    linkedin: in/afonsoavr
    instagram: afonsoavr

defaults:
  - scope:
      path: ""
    values:
      layout: "post"
      image: /assets/images/default.jpg
      og:
        type: website

comments:
  provider: disqus
disqus:
  shortname: afonsoaugusto-github-io

google_analytics: G-8TFSN8203P
