title: Afonso Rodrigues blog's
email: afonsoaugustoventura@gmail.com
description: >-
  Anotações, Scripts e Dicas de DevOps, SRE, Kubernetes e AWS
baseurl: ""
url: "https://afonsorodrigues.com"
lang: "pt-BR"
encoding: "utf-8"

twitter_username: Afonsoavr
github_username: afonsoaugusto

# SEO
seo:
  type: "Person"
  name: "Afonso Rodrigues"
  description: "Anotações, Scripts e Dicas de DevOps e SRE"
  url: "https://afonsorodrigues.com"
  twitter: "@Afonsoavr"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-toc
  - kramdown
  - rouge

highlighter: rouge

kramdown:
  input: GFM

minima:
  name: Afonso Rodrigues
  social_links:
    twitter: Afonsoavr
    github: afonsoaugusto
    linkedin: in/afonsoavr
    instagram: afonsoavr

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: "default"
  - scope:
      path: ""
      type: posts
    values:
      layout: "default"
      image: /assets/images/default.jpg
      og:
        type: article

comments:
  provider: disqus
disqus:
  shortname: afonsoaugusto-github-io

google_analytics: G-8TFSN8203P

# Pagination settings
pagination:
  enabled: true
  per_page: 5
  permalink: /page/:num/
  title: ':title - Página :num'
  sort_reverse: true
  trail:
    before: 2
    after: 2