title: Afonso Rodrigues blog's
email: afonsoaugustoventura@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Anotações, Scripts e Dicas
baseurl: "" # the subpath of your site, e.g. /blog
url: https://afonsoaugusto.github.io/ # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Afonsoavr
github_username: afonsoaugusto

# Build settings
markdown: kramdown
permalink: /:categories/:title/
# theme: minima
remote_theme: jekyll/minima
#remote_theme: afonsoaugusto/plainwhite-jekyll
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-remote-include
  - kramdown
  - rouge

highlighter: rouge

kramdown:
  input: GFM

minima:
  name: Afonso Rodrigues

  social_links:
    twitter: Afonsoavr
    github: afonsoaugusto
    linkedin: in/afonsoavr # format: locale/username
    instagram: afonsoavr

comments:
  provider: disqus
disqus:
  shortname: afonsoaugusto-github-io

# site:
#   google_analytics: G-8TFSN8203P
google_analytics: G-8TFSN8203P
